language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "11"
  - "10"
script:
  - cd packages/bloc && npm i && npm run test:prod && npm run build
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
