name: bloc.js

on:
  push:
    paths:
      - "packages/bloc/**"
      - ".github/workflows/bloc.yaml"

  pull_request:
    paths:
      - "packages/bloc/**"
      - ".github/workflows/bloc.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/bloc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npm run test:prod
      - run: npm run build
      - run: bash <(curl -s https://codecov.io/bash)
